import type { Metadata } from "next";
import { Inter, DM_Serif_Display, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./Provider";

const poppins = Poppins({
	subsets: ["latin"],
	weight: ["400", "600"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={poppins.className}>{children}</body>
			</Providers>
		</html>
	);
}
